branch-defaults:
  main:
    environment: processing
    group_suffix: null
global:
  application_name: ltc-data-processing
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 19.03.13-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
